### ISSUE TITLE
Website down (404 not found)

### ISSUE THREAD

**Issue by RainbowSaga** [Khanhtran47/remix-movie#241]
![Screenshot 2022-10-27 142139](https://user-images.githubusercontent.com/117321707/199619329-ca7e0221-8bde-4930-a2d3-02eb48270909.png)

Plz fix soon.. :pray: :pray:
i really like this app

**Comment by Khanhtran47** [comment]
@RainbowSaga First, I want to make sure that this is a project for learning purpose, the deployment is for demo only, not for using. And also, this is not an issue that we can fix because someone was tried to scrap our deployment, the deployment has reach its limit and Vercel has blocked our project. Therefore, we keep developing from localhost from now on and if you really want to use our app, just fork or clone repo and deploy yourself.
